# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gltr < Formula
  desc "A CLI for low friction data science"
  homepage "https://github.com/gltr-sh/gltr"
  version "0.0.1"
  license "BSD-3-Clause"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/gltr-sh/gltr/releases/download/v0.0.1/gltr_Darwin_arm64.tar.gz"
      sha256 "88d569aa7465b26c11281268ef4b8d30f9a13cb1f79728bb057b4eb78d1e4891"

      def install
        bin.install "gltr"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/gltr-sh/gltr/releases/download/v0.0.1/gltr_Darwin_x86_64.tar.gz"
      sha256 "b068d7f681731a47b558b8b411be73d1bf9ae50f64346b6e5f71987d658cf9cd"

      def install
        bin.install "gltr"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/gltr-sh/gltr/releases/download/v0.0.1/gltr_Linux_arm64.tar.gz"
      sha256 "9eec3d2ed3c444eeadf1bf8f56d6e726e7f21e8c72638f2fdbde179c9f8f028f"

      def install
        bin.install "gltr"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/gltr-sh/gltr/releases/download/v0.0.1/gltr_Linux_x86_64.tar.gz"
      sha256 "26548ca978b71c8c08a0fff1998c7843a733faf76e7441ac21f87f0252705fb6"

      def install
        bin.install "gltr"
      end
    end
  end
end
